### ISSUE TITLE
yarn add command error

### ISSUE THREAD

**Issue by bparanj** [gauravtiwari/webpacker-example-app#1]
I am getting the following error when I run the yarn add command:

```
./bin/yarn add —-dev node-sass style-loader css-loader sass-loader
yarn add v0.20.3
[1/4] 🔍  Resolving packages...
error Couldn't find package "—-dev" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
$ yarn add —-dev node-sass style-loader css-loader sass-loader
```

**Comment by gauravtiwari** [comment]
@bparanj Ohh, looks like one of the hyphen is strange (due to copy paste from medium). Please try this 👍 

```bash
./bin/yarn add --dev node-sass style-loader css-loader sass-loader
```

**Comment by gauravtiwari** [comment]
Please close this issue if above fixed it :)

**Comment by bparanj** [comment]
I got past that problem. Now when I start the server I get this error:

```
bundle exec foreman start -f Procfile.dev
16:48:54 web.1  | started with pid 85094
16:48:54 hot.1  | started with pid 85095
16:48:55 hot.1  | module.js:471
16:48:55 hot.1  |     throw err;
16:48:55 hot.1  |     ^
16:48:55 hot.1  | 
16:48:55 hot.1  | Error: Cannot find module 'webpack'
16:48:55 hot.1  |     at Function.Module._resolveFilename (module.js:469:15)
16:48:55 hot.1  |     at Function.Module._load (module.js:417:25)
16:48:55 hot.1  |     at Module.require (module.js:497:17)
16:48:55 hot.1  |     at require (internal/module.js:20:19)
16:48:55 hot.1  |     at Object.<anonymous> (/Users/bparanj/temp/r51/node_modules/webpack-dev-server/lib/Server.js:15:17)
16:48:55 hot.1  |     at Module._compile (module.js:570:32)
16:48:55 hot.1  |     at Object.Module._extensions..js (module.js:579:10)
16:48:55 hot.1  |     at Module.load (module.js:487:32)
16:48:55 hot.1  |     at tryModuleLoad (module.js:446:12)
16:48:55 hot.1  |     at Function.Module._load (module.js:438:3)
16:48:55 hot.1  | exited with code 1
16:48:55 system | sending SIGTERM to all processes
16:48:55 web.1  | terminated by SIGTERM
```

**Comment by gauravtiwari** [comment]
@bparanj Ohh, this seems like you haven't installed the node_modules. Please could you clone this repo and follow the readme section  - `Running in Development`

**Comment by gauravtiwari** [comment]
Closing due to inactivity.
